/** Versioned receipt policy owned by the delegated-agent/Drovr boundary. */

export const DELEGATE_RECEIPT_SCHEMA_FIELDS = new Map([
  ["flow.delegate-cancellation-receipt/v1", new Set([
    "delegate_attempt_id",
    "delegate_effect_id",
    "drovr_watermark",
    "schema",
    "terminal_disposition",
    "turn_id",
  ])],
  ["flow.delegate-evidence/v1", new Set([
    "attempt_id",
    "authority_terminal_disposition",
    "card_id",
    "correlated_output",
    "drovr_watermark",
    "evidence_safety_binding",
    "evidence_safety_receipt",
    "operational_failure",
    "quarantine_record",
    "route_binding",
    "schema",
    "settlement_proof",
    "terminal_disposition",
    "turn_id",
    "validated_output",
    "validator_receipts",
  ])],
  ["drovr.turn-settlement-proof/v1", new Set([
    "classification",
    "configuration_watermark",
    "description_digest",
    "launch_comparison_key",
    "ordered_inputs",
    "record_sha256",
    "schema",
  ])],
  ["drovr.turn-watermark/v1", new Set([
    "content_sha256",
    "schema",
    "sequence",
  ])],
  ["flow.delegate-quarantine/v1", new Set([
    "attempt_id",
    "card_id",
    "correlated_output",
    "drovr_watermark",
    "evidence_safety_binding",
    "evidence_safety_receipt",
    "quarantine_reason",
    "route_binding",
    "schema",
    "settlement_proof",
    "terminal_disposition",
    "turn_id",
    "validator_receipts",
  ])],
]);

export const DELEGATE_REQUIRED_RECEIPT_FIELDS = new Map([
  ["flow.delegate-evidence/v1", [
    "attempt_id",
    "card_id",
    "turn_id",
    "route_binding",
    "validator_receipts",
  ]],
  ["flow.delegate-quarantine/v1", [
    "attempt_id",
    "card_id",
    "turn_id",
    "route_binding",
    "quarantine_reason",
    "validator_receipts",
  ]],
]);

export const DELEGATE_NESTED_FIELDS = new Set([
  "agent_id",
  "authority",
  "authority_terminal_disposition",
  "caller_key",
  "configuration_watermark",
  "correlated_output",
  "delivery_proof",
  "delegation",
  "description_digest",
  "durable_holder",
  "evidence",
  "evidence_digest",
  "evidence_safety_accepted",
  "evidence_safety_binding",
  "evidence_safety_rejection",
  "evidence_safety_receipt",
  "launch_comparison_key",
  "managed_agent_binding",
  "ordered_inputs",
  "payload_sha256",
  "quarantine_record",
  "record_sha256",
  "sequence",
  "terminal_disposition",
  "turn",
  "turn_disposition",
  "turn_id",
  "validated_output",
  "validator_receipts",
]);
