/** Versioned receipt policy owned by the delegated-agent/Drovr boundary. */

export const DELEGATE_FAILURE_OBSERVATION_SCHEMA =
  "flow.delegate-failure-observation/v1";

export const DELEGATE_FAILURE_OBSERVATION_FIELDS = Object.freeze([
  "absence_proven",
  "code",
  "drovr",
  "request_envelope",
  "retryable",
  "resource_projection",
  "schema",
  "stage",
]);

export const DELEGATE_RECEIPT_SCHEMA_FIELDS = new Map([
  ["flow.delegate-cancellation-receipt/v1", new Set([
    "delegate_attempt_id",
    "delegate_effect_id",
    "drovr_watermark",
    "schema",
    "terminal_disposition",
    "turn_id",
  ])],
  ["flow.delegate-evidence/v1", new Set([
    "attempt_id",
    "authority_terminal_disposition",
    "card_id",
    "correlated_output",
    "drovr_watermark",
    "evidence_safety_binding",
    "evidence_safety_receipt",
    "operational_failure",
    "quarantine_record",
    "route_binding",
    "schema",
    "settlement_proof",
    "terminal_disposition",
    "turn_id",
    "validated_output",
    "validator_receipts",
  ])],
  ["drovr.turn-settlement-proof/v1", new Set([
    "classification",
    "configuration_watermark",
    "description_digest",
    "launch_comparison_key",
    "ordered_inputs",
    "record_sha256",
    "schema",
  ])],
  ["drovr.turn-watermark/v1", new Set([
    "content_sha256",
    "schema",
    "sequence",
  ])],
  ["flow.delegate-quarantine/v1", new Set([
    "attempt_id",
    "card_id",
    "correlated_output",
    "drovr_watermark",
    "evidence_safety_binding",
    "evidence_safety_receipt",
    "quarantine_reason",
    "route_binding",
    "schema",
    "settlement_proof",
    "terminal_disposition",
    "turn_id",
    "validator_receipts",
  ])],
  ["flow.delegated-agent-resource-projection/v1", new Set([
    "binding",
    "binding_digest",
    "cleanup_receipt",
    "delegation",
    "legal_next_actions",
    "operation",
    "reason",
    "resource_key",
    "schema",
    "status",
    "watermark",
    "workspace",
  ])],
  ["flow.delegated-agent-resource-binding/v1", new Set([
    "binding_digest",
    "launch_binding",
    "managed_runtime_evidence_digest",
    "native_session",
    "owner",
    "resource_key",
    "schema",
    "workspace_claim",
    "delegation",
  ])],
  ["flow.delegated-agent-resource-watermark/v1", new Set([
    "agent_id",
    "authority",
    "authority_watermark",
    "group_id",
    "record_sha256",
    "resource_key",
    "schema",
    "task_id",
  ])],
  ["drovr.registry-authority-watermark/v1", new Set([
    "agents_count",
    "agents_sha256",
    "authority",
    "blocks_count",
    "blocks_sha256",
    "generation",
    "groups_count",
    "groups_sha256",
    "registry_sha256",
    "schema",
    "tasks_count",
    "tasks_sha256",
    "turns_count",
    "turns_sha256",
  ])],
  ["flow.delegated-agent-resource-cleanup-receipt/v1", new Set([
    "agent_id",
    "agent_retirement",
    "authority_watermark",
    "group_id",
    "proof",
    "schema",
    "task_id",
  ])],
  ["drovr.agent-retirement-receipt/v1", new Set([
    "agent_id",
    "interrupted_turns",
    "observation",
    "pane",
    "proof",
    "recorded_at",
    "schema",
  ])],
]);

export const DELEGATE_REQUIRED_RECEIPT_FIELDS = new Map([
  ["flow.delegate-evidence/v1", [
    "attempt_id",
    "card_id",
    "turn_id",
    "route_binding",
    "validator_receipts",
  ]],
  ["flow.delegate-quarantine/v1", [
    "attempt_id",
    "card_id",
    "turn_id",
    "route_binding",
    "quarantine_reason",
    "validator_receipts",
  ]],
]);

export const DELEGATE_NESTED_FIELDS = new Set([
  "agent_id",
  "absence_proven",
  "authority",
  "authority_watermark",
  "authority_terminal_disposition",
  "caller_key",
  "card_id",
  "configuration_watermark",
  "correlated_output",
  "delivery_proof",
  "delegation",
  "classification",
  "description_digest",
  "durable_holder",
  "evidence",
  "evidence_digest",
  "evidence_safety_accepted",
  "evidence_safety_binding",
  "evidence_safety_rejection",
  "evidence_safety_receipt",
  "effective_authority_comparison_key",
  "kind",
  "access",
  "route_key",
  "managed_agent_binding_id",
  "generation",
  "mutation_epoch",
  "fingerprint",
  "contract",
  "subject_id",
  "operation",
  "effect_created",
  "envelope_digest",
  "field_digests",
  "fields_present",
  "launch_comparison_key",
  "launch_binding",
  "legal_next_actions",
  "managed_agent_binding",
  "managed_runtime_evidence_digest",
  "message",
  "native_dispatch_started",
  "ordered_inputs",
  "owner",
  "payload_sha256",
  "quarantine_record",
  "resource_disposition",
  "resource_binding",
  "resource_projection",
  "record_sha256",
  "resource_key",
  "run_id",
  "sequence",
  "terminal_disposition",
  "turn",
  "turn_disposition",
  "turn_id",
  "task_id",
  "group_id",
  "binding",
  "binding_digest",
  "native_session",
  "workspace",
  "workspace_claim",
  "turn_created",
  "outcome",
  "validated_output",
  "validator_receipts",
]);
