/** Versioned receipt policy owned by feature and Work-domain modules. */

export const FEATURE_WORK_RECEIPT_SCHEMA_FIELDS = new Map([
  ["flow.feature-test-receipt/v1", new Set([
    "attempt_id",
    "card_id",
    "effect_id",
    "environment_fingerprint",
    "environment_status",
    "idempotency_key",
    "intended_failure",
    "operation_contract",
    "outcome",
    "phase",
    "schema",
    "slice_id",
    "source_authority_watermark",
    "workspace",
  ])],
  ["work.feature-test-receipt/v1", new Set([
    "attempt_id",
    "card_id",
    "effect_id",
    "environment_fingerprint",
    "environment_status",
    "idempotency_key",
    "intended_failure",
    "operation_contract",
    "outcome",
    "phase",
    "schema",
    "slice_id",
    "source_authority_watermark",
    "workspace",
  ])],
  ["work.feature-verification-receipt/v1", new Set([
    "acceptance_criteria",
    "attempt_id",
    "brief_id",
    "discriminating_evidence",
    "effect_id",
    "idempotency_key",
    "operation_contract",
    "receipt_digest",
    "schema",
    "selected_evidence_fingerprint",
    "self_digest",
    "source_authority_watermark",
    "workspace",
  ])],
  ["work.feature-critique-receipt/v1", new Set([
    "delegate_evidence",
    "effect_id",
    "findings",
    "idempotency_key",
    "operation_contract",
    "receipt_digest",
    "schema",
    "self_digest",
    "source_authority_watermark",
  ])],
  ["work.feature-setup-receipt/v1", new Set([
    "evidence_role",
    "schema",
    "setup_id",
  ])],
  ["flow.feature-seal-receipt/v1", new Set([
    "git_retention",
    "publication_digest",
    "review_candidate",
    "schema",
  ])],
  ["flow.feature-discriminating-evidence/v1", new Set([
    "assertion_receipt_digest",
    "distinguished",
    "kind",
    "non_destructive",
    "post_mutation_fingerprint",
    "satisfied",
    "schema",
    "selected_fingerprint",
    "test_failures",
  ])],
  ["flow.feature-test-selection/v1", new Set([
    "fingerprint",
    "schema",
    "slices",
  ])],
  ["flow.feature-safe-baseline/v1", new Set([
    "fingerprint",
    "schema",
  ])],
  ["flow.feature-compensating-assertion/v1", new Set([
    "assertion",
    "kind",
    "schema",
  ])],
  ["flow.feature-test-failure/v1", new Set([
    "card_id",
    "effect_id",
    "receipt_digest",
    "schema",
    "slice_id",
  ])],
  ["flow.feature-seal/v1", new Set([
    "artifacts",
    "candidate_fingerprint",
    "candidate_id",
    "critique",
    "git",
    "git_retention",
    "schema",
    "verification",
    "workspace",
  ])],
  ["work.review-candidate/v1", new Set([
    "artifacts",
    "candidate_fingerprint",
    "candidate_id",
    "critique",
    "git",
    "git_retention",
    "schema",
    "verification",
    "workspace",
  ])],
  ["work.workspace/v1", new Set([
    "contract",
    "fingerprint",
    "generation",
    "git",
    "mutation_epoch",
    "subject_id",
  ])],
]);

export const FEATURE_WORK_NESTED_FIELDS = new Set([
  "artifact_schema",
  "artifacts",
  "assertion_receipt_digest",
  "bytes_digest",
  "candidate_fingerprint",
  "candidate_id",
  "criterion",
  "critique",
  "evidence_role",
  "environment_fingerprint",
  "environment_status",
  "git",
  "git_retention",
  "non_destructive",
  "phase",
  "post_mutation_fingerprint",
  "publication_digest",
  "receipt_digest",
  "satisfied",
  "selected_fingerprint",
  "self_digest",
  "setup_id",
  "slice_id",
  "test_failures",
  "verdict",
  "verification",
  "workspace",
]);
